
[behaviour]
	#This section determines the behaviour of the Weeping Angels.
	#Range for player visibility check.
	#Range: 1 ~ 100
	stalk_range = 65
	#Allow angels to break light-emitting blocks?
	block_breaking = false

[damage]
	#Type of hurt inflicted by angels.
	#Allowed Values: PICKAXE, PICKAXE_AND_GENERATOR, NONE, GENERATOR, ANYTHING
	hurt_type = "ANYTHING"

[teleporting]
	#Range for teleportation.
	#Range: > 1
	teleport_range = 20
	#Allow teleporting across dimensions?
	interdimensional_teleporting = false
	#Allow Angel theft?
	angel_theft = false
	#Chance of teleportation occurring.
	#Range: 1 ~ 100
	teleport_chance = 50
	#Dimensions where teleportation is banned.
	banned_dimensions = ["minecraft:the_end", "minecraft:the_nether"]

